[package]
name = "minetv"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
winapi = { version = "0.3.6", features = ["winuser"] }
detour = "0.5.0"